version: "3"
services:
  cas1:
    image: cassandra:latest
    container_name: cas1
    hostname: cas1
    environment:
      - MAX_HEAP_SIZE=128M
      - HEAP_NEWSIZE=64M
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cas1
      - CASSANDRA_LISTEN_ADDRESS=cas1
      - CASSANDRA_BROADCAST_ADDRESS=cas1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
    ports:
      - "9042:9042"
    networks:
      - cassandra_net

  cas2:
    image: cassandra:latest
    container_name: cas2
    hostname: cas2
    environment:
      - MAX_HEAP_SIZE=128M
      - HEAP_NEWSIZE=64M
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cas1
      - CASSANDRA_LISTEN_ADDRESS=cas2
      - CASSANDRA_BROADCAST_ADDRESS=cas2
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1
    ports:
      - "9043:9042"
    depends_on:
      - cas1
    networks:
      - cassandra_net

networks:
  cassandra_net:
