name: React Frontend CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22  # or whatever Node.js version you're using

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Build Vite app
      run: npm run build
